# Generated by Django 4.2.1 on 2023-07-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WPF", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastTask",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("turbine_id", models.CharField(max_length=20)),
                ("model_id", models.CharField(max_length=20)),
                ("task_status", models.CharField(max_length=20)),
                ("task_startTime", models.CharField(max_length=40)),
                ("task_endTime", models.CharField(max_length=40)),
                ("task_finishTime", models.CharField(max_length=40)),
                ("task_comment", models.CharField(max_length=80)),
                ("task_resultPath", models.CharField(max_length=80)),
            ],
        ),
    ]
