# Generated by Django 4.2.1 on 2023-07-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WPF", "0002_forecasttask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forecasttask",
            name="task_resultPath",
        ),
        migrations.AddField(
            model_name="forecasttask",
            name="data_id",
            field=models.CharField(default="0", max_length=20),
        ),
        migrations.AddField(
            model_name="forecasttask",
            name="result_id",
            field=models.CharField(default="0", max_length=20),
        ),
    ]
