# Generated by Django 4.2.1 on 2023-07-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WPF", "0003_remove_forecasttask_task_resultpath_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecasttask",
            name="data_name",
            field=models.CharField(default="0", max_length=20),
        ),
    ]
