# Generated by Django 4.2.1 on 2023-07-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WPF", "0004_forecasttask_data_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecasttask",
            name="model_type",
            field=models.CharField(default="0", max_length=20),
        ),
    ]
